/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the browser application shell
         * @description Returns the single client-routed HTML document. The browser loads its
         *     state from `/api/v1/bootstrap` and routes between conversations itself
         *     without requesting another document.
         */
        get: operations["getShell"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/s/{forum_id}/{session_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /**
         * Get the shell for a session deep link
         * @description Returns the same document as `/`. The trailing slash is required.
         *
         *     The identifiers are neither validated nor resolved here: an unknown,
         *     malformed, or unopened session still receives the shell with status 200.
         *     The browser reads them from its own location and opens the session
         *     through `POST /api/v1/forums/{forum_id}/sessions/{session_id}/open`.
         */
        get: operations["getSessionShell"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check service readiness */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get initial navigation and discovery state
         * @description Returns the initial built-in IDs, the effective persona and character
         *     rosters, forum membership, and all recent sessions ordered newest first.
         *
         *     The persona, character, and forum rosters are loaded once at server
         *     startup, so workspace configuration changes require a restart. Sessions
         *     are read from storage on every request, so `recent_sessions` includes
         *     sessions created since startup.
         */
        get: operations["getBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe character identifier. */
                character_id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        /**
         * Get character details
         * @description Returns the character summary and its verbatim Markdown definition.
         *     The built-in Assistant returns the embedded application guide.
         */
        get: operations["getCharacter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forums/{forum_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
            };
            cookie?: never;
        };
        /**
         * List a forum's sessions
         * @description Lists stored sessions and whether each has a live runtime. The built-in
         *     Entrance forum returns only its process-local Welcome session.
         */
        get: operations["listSessions"];
        put?: never;
        /**
         * Create a stored session
         * @description Creates the session without opening a live runtime for it. The label is
         *     stored as given; an empty label is replaced by the generated session ID,
         *     so the returned label may differ from the requested one.
         *
         *     Only workspace forums accept creation. The built-in Entrance forum has no
         *     workspace directory, so creating a session in it answers `404` with
         *     `not_found`; its Welcome session is the only session it ever lists.
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forums/{forum_id}/sessions/{session_id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open or reattach to a session
         * @description Starts the session's live runtime, or reattaches to its existing runtime.
         *     On success, live-session operations become available beneath the session's
         *     `/s/{forum_id}/{session_id}/api/v1` path.
         */
        post: operations["openSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/s/{forum_id}/{session_id}/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** Get the authoritative live-session snapshot */
        get: operations["getSessionSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/s/{forum_id}/{session_id}/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /**
         * Stream live-session updates
         * @description Opens the session's single allowed Server-Sent Events connection.
         *     The first record is a `snapshot` event whose JSON data is a
         *     `SessionSnapshot`. Later records are either replacement `snapshot`
         *     events or `append` events whose JSON data is an `AppendEvent`.
         *     Comment-only `: heartbeat` records keep an idle connection alive.
         *
         *     `Last-Event-ID` is ignored; reconnecting starts with a fresh snapshot.
         */
        get: operations["streamSessionEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/s/{forum_id}/{session_id}/api/v1/input": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit user input
         * @description Submits text through the session's shared input path. `persona` is a
         *     stable attribution ID, not an authentication identity.
         */
        post: operations["submitInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/s/{forum_id}/{session_id}/api/v1/actions/stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request that generation stop */
        post: operations["stopGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/s/{forum_id}/{session_id}/api/v1/actions/default-character": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the session's default character */
        post: operations["setDefaultCharacter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example lobby */
        Identifier: string;
        EmptyObject: Record<string, never>;
        Health: {
            /** @constant */
            ready: true;
            live_session_count: number;
        };
        PersonaSummary: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            description?: string;
        };
        /**
         * @description How the browser sets this character's words, so a reader can tell one
         *     speaker from another without reading every name. A closed vocabulary:
         *     the browser owns the actual typefaces and sizes and pairs each choice
         *     with a dark-mode variant, and a workspace cannot supply styling of its
         *     own. Always present, defaults included.
         */
        CharacterAppearance: {
            /** @enum {string} */
            font: "sans" | "serif" | "mono";
            /** @enum {string} */
            style: "normal" | "italic";
            /** @enum {string} */
            weight: "normal" | "bold";
            /** @enum {string} */
            size: "small" | "normal" | "large";
        };
        CharacterSummary: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            description?: string;
            appearance: components["schemas"]["CharacterAppearance"];
        };
        ForumSummary: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            default_character_id: components["schemas"]["Identifier"];
            members: components["schemas"]["CharacterSummary"][];
        };
        SessionListing: {
            id: components["schemas"]["Identifier"];
            label: string;
            live: boolean;
            updated_at: components["schemas"]["UnixTimestamp"];
        };
        RecentSession: {
            forum_id: components["schemas"]["Identifier"];
            session_id: components["schemas"]["Identifier"];
            session_label: string;
            updated_at: components["schemas"]["UnixTimestamp"];
        };
        Bootstrap: {
            initial_persona_id: components["schemas"]["Identifier"];
            initial_forum_id: components["schemas"]["Identifier"];
            initial_session_id: components["schemas"]["Identifier"];
            personas: components["schemas"]["PersonaSummary"][];
            characters: components["schemas"]["CharacterSummary"][];
            forums: components["schemas"]["ForumSummary"][];
            /** @description All sessions ordered by `updated_at` descending. */
            recent_sessions: components["schemas"]["RecentSession"][];
        };
        CharacterDetail: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            description?: string;
            appearance: components["schemas"]["CharacterAppearance"];
            character_markdown: string;
        };
        CreateSessionRequest: {
            label: string;
        };
        CreateSessionResult: {
            id: components["schemas"]["Identifier"];
            label: string;
        };
        OpenSessionResult: {
            forum_id: components["schemas"]["Identifier"];
            session_id: components["schemas"]["Identifier"];
        };
        InputRequest: {
            /** @description Stable persona attribution ID; not an authentication credential. */
            persona: string;
            /** @description Input text, limited by the server's configured prompt byte limit. */
            text: string;
        };
        SetDefaultCharacterRequest: {
            character_id: string;
        };
        CommandResult: {
            clear_input: boolean;
            notice?: string;
        };
        TranscriptEntry: {
            id: components["schemas"]["UnsignedInteger"];
            /** @enum {string} */
            kind: "human" | "character" | "notice" | "error";
            participant_id: string;
            display_name: string;
            addressed_to: string;
            addressed_to_name: string;
            text: string;
            /** @enum {string} */
            status: "complete" | "streaming" | "cancelled" | "failed";
            request_id?: components["schemas"]["UnsignedInteger"];
        };
        GenerationState: {
            active: boolean;
            request_id?: components["schemas"]["UnsignedInteger"];
            character_id: string;
            character_display_name: string;
            /** @enum {string} */
            phase: "waiting" | "reasoning" | "answering" | "stopping";
            reasoning_text: string;
        };
        SessionSnapshot: {
            forum: components["schemas"]["ForumSummary"];
            session_id: components["schemas"]["Identifier"];
            session_label: string;
            characters: components["schemas"]["CharacterSummary"][];
            default_character_id: components["schemas"]["Identifier"];
            transcript: components["schemas"]["TranscriptEntry"][];
            generation: components["schemas"]["GenerationState"];
            notice?: string;
            /** @enum {string} */
            lifecycle: "starting" | "running" | "stopping";
            /** @enum {string} */
            shutdown_reason?: "browser_disconnected" | "session_failed" | "server_stopping";
        };
        AppendTargetEntry: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "entry";
            entry_id: components["schemas"]["UnsignedInteger"];
        };
        AppendTargetReasoning: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "reasoning";
            request_id: components["schemas"]["UnsignedInteger"];
        };
        AppendTarget: components["schemas"]["AppendTargetEntry"] | components["schemas"]["AppendTargetReasoning"];
        AppendEvent: {
            target: components["schemas"]["AppendTarget"];
            text: string;
            seq: components["schemas"]["UnsignedInteger"];
        };
        ErrorResponse: {
            error: {
                /** @enum {string} */
                code: "not_found" | "bad_request" | "body_too_large" | "prompt_too_large" | "forbidden_origin" | "internal_error" | "session_busy" | "session_stopping" | "session_limit_reached" | "session_open_timeout" | "server_stopping" | "session_not_live" | "browser_stream_in_use" | "command_timeout" | "command_queue_full";
                message: string;
            };
        };
        /**
         * Format: int64
         * @description Whole seconds since the Unix epoch.
         */
        UnixTimestamp: number;
        UnsignedInteger: number;
    };
    responses: {
        /**
         * @description Content type is not JSON, or the JSON body has an invalid shape.
         *     `error.code` is `bad_request`.
         */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Origin does not match Host. `error.code` is `forbidden_origin`. */
        ForbiddenMutation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description The route identifier or selected resource was not found.
         *     `error.code` is `not_found`.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description The selected session does not have a live runtime.
         *     `error.code` is `session_not_live`.
         */
        SessionNotLive: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description The JSON request body exceeds the configured size limit.
         *     `error.code` is `body_too_large`.
         */
        BodyTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description The request failed unexpectedly.
         *     `error.code` is `internal_error`.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The client-routed application document, served as UTF-8 HTML. */
        Shell: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/html": string;
            };
        };
        /**
         * @description The command queue is full, the command timed out, or the server is
         *     stopping. `error.code` is `command_queue_full`, `command_timeout`, or
         *     `server_stopping`. On `command_timeout` the command's outcome is
         *     unknown: it may still be applied.
         */
        CommandUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Command completed at the live-session boundary. */
        CommandAccepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CommandResult"];
            };
        };
    };
    parameters: {
        /** @description Stable URL-safe forum identifier. */
        ForumId: components["schemas"]["Identifier"];
        /** @description Stable URL-safe session identifier. */
        SessionId: components["schemas"]["Identifier"];
        /** @description Stable URL-safe character identifier. */
        CharacterId: components["schemas"]["Identifier"];
    };
    requestBodies: {
        EmptyJsonObject: {
            content: {
                "application/json": components["schemas"]["EmptyObject"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getShell: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Shell"];
            500: components["responses"]["InternalError"];
        };
    };
    getSessionShell: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Shell"];
            500: components["responses"]["InternalError"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is ready to accept requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bootstrap state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bootstrap"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe character identifier. */
                character_id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Character details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListing"][];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Session created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["ForbiddenMutation"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["BodyTooLarge"];
            500: components["responses"]["InternalError"];
        };
    };
    openSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["EmptyJsonObject"];
        responses: {
            /** @description Session is open. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenSessionResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["ForbiddenMutation"];
            404: components["responses"]["NotFound"];
            /**
             * @description The session is busy or stopping. `error.code` is `session_busy` when
             *     its storage lease is held by another CHA process,
             *     or `session_stopping` while its previous runtime is still shutting
             *     down. Both are retryable.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            413: components["responses"]["BodyTooLarge"];
            500: components["responses"]["InternalError"];
            /**
             * @description Session limit, open timeout, or server shutdown prevented opening.
             *     `error.code` is `session_limit_reached`, `session_open_timeout`, or
             *     `server_stopping`. On `session_open_timeout` the session may still
             *     finish opening, so the request can be retried.
             */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSessionSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["SessionNotLive"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["CommandUnavailable"];
        };
    };
    streamSessionEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description SSE stream containing `snapshot` and `append` events. Event data is
             *     one compact JSON value on the `data:` line.
             */
            200: {
                headers: {
                    "Cache-Control"?: "no-cache";
                    "X-Accel-Buffering"?: "no";
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
            /**
             * @description Session is not live or already has an event stream. `error.code` is
             *     `session_not_live`, or `browser_stream_in_use` when the session's one
             *     allowed connection is already held by another browser page.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
            503: components["responses"]["CommandUnavailable"];
        };
    };
    submitInput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InputRequest"];
            };
        };
        responses: {
            200: components["responses"]["CommandAccepted"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["ForbiddenMutation"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["SessionNotLive"];
            /**
             * @description Request body or prompt text exceeds its configured limit.
             *     `error.code` is `body_too_large` for the whole request body, or
             *     `prompt_too_large` for the `text` field alone.
             */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
            503: components["responses"]["CommandUnavailable"];
        };
    };
    stopGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["EmptyJsonObject"];
        responses: {
            200: components["responses"]["CommandAccepted"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["ForbiddenMutation"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["SessionNotLive"];
            413: components["responses"]["BodyTooLarge"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["CommandUnavailable"];
        };
    };
    setDefaultCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDefaultCharacterRequest"];
            };
        };
        responses: {
            200: components["responses"]["CommandAccepted"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["ForbiddenMutation"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["SessionNotLive"];
            413: components["responses"]["BodyTooLarge"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["CommandUnavailable"];
        };
    };
}
