/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the browser application shell
         * @description Returns the single client-routed HTML document. The browser loads its
         *     state from `/api/v1/bootstrap` and routes between conversations itself
         *     without requesting another document.
         */
        get: operations["getShell"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/s/{forum_id}/{session_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /**
         * Get the shell for a session deep link
         * @description Returns the same document as `/`. The trailing slash is required.
         *
         *     The identifiers are neither validated nor resolved here: an unknown,
         *     malformed, or unopened session still receives the shell with status 200.
         *     The browser reads them from its own location and opens the session
         *     through `POST /api/v1/forums/{forum_id}/sessions/{session_id}/open`.
         */
        get: operations["getSessionShell"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check service readiness */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get initial navigation and discovery state
         * @description Returns the initial forum and character rosters, including each forum's
         *     fixed persona, and all recent sessions ordered newest first.
         *
         *     The character and forum rosters are loaded once at server startup, so
         *     workspace configuration changes require a restart. Sessions
         *     are read from storage on every request, so `recent_sessions` includes
         *     sessions created since startup.
         */
        get: operations["getBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe character identifier. */
                character_id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        /**
         * Get character details
         * @description Returns the character summary, its template-expanded Markdown
         *     definition, and the provider/style settings the editor needs. The
         *     built-in Assistant returns the embedded application guide and is not
         *     writable.
         */
        get: operations["getCharacter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a character's provider and style
         * @description Rewrites `provider` and `style` in the character's `character.toml`.
         *     `null` erases the key. A name whose config does not load is `400` and
         *     leaves the file untouched. The built-in Assistant, a missing character,
         *     and a character whose file cannot be read are `404`.
         *
         *     After a write that actually changes a value, the server asks live
         *     sessions the change can affect to shut down with `reloading`. A
         *     provider-only save does not restart sessions in forums that override
         *     the provider. The server does not reopen anything.
         */
        patch: operations["updateCharacter"];
        trace?: never;
    };
    "/api/v1/personas/{persona_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe persona identifier. */
                persona_id: components["parameters"]["PersonaId"];
            };
            cookie?: never;
        };
        /**
         * Get persona details
         * @description Returns the persona summary and its `PERSONA.md` description verbatim.
         *     `persona_markdown` is empty for a persona that configures none.
         */
        get: operations["getPersona"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forums/{forum_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
            };
            cookie?: never;
        };
        /**
         * Get forum details
         * @description Returns the forum summary and its `FORUM.md` verbatim. That file is
         *     also the forum's system prompt, and is published whole by design.
         *     Template placeholders such as `$${character.display_name}` are not
         *     expanded, because a description belongs to no single member.
         *     `forum_markdown` is empty for a forum that has no `FORUM.md`, including
         *     the built-in Entrance.
         */
        get: operations["getForum"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forums/{forum_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
            };
            cookie?: never;
        };
        /**
         * List a forum's sessions
         * @description Lists stored sessions and whether each has a live runtime. The built-in
         *     Entrance forum returns only its process-local Welcome session.
         */
        get: operations["listSessions"];
        put?: never;
        /**
         * Create a stored session
         * @description Creates the session without opening a live runtime for it. The label is
         *     stored as given; an empty label is replaced by the generated session ID,
         *     so the returned label may differ from the requested one.
         *
         *     A non-empty label must be valid UTF-8, contain at most 200 Unicode code
         *     points, contain no control characters or line breaks, and have no
         *     leading or trailing Unicode whitespace. Invalid labels answer `400`
         *     with `bad_request`.
         *
         *     Only workspace forums accept creation. The built-in Entrance forum has no
         *     workspace directory, so creating a session in it answers `404` with
         *     `not_found`; its Welcome session is the only session it ever lists.
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forums/{forum_id}/sessions/{session_id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open or reattach to a session
         * @description Starts the session's live runtime, or reattaches to its existing runtime.
         *     On success, live-session operations become available beneath the session's
         *     `/s/{forum_id}/{session_id}/api/v1` path.
         */
        post: operations["openSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forums/{forum_id}/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Move a session into recoverable deleted storage
         * @description Removes the session from CHA without erasing it. Its database is moved
         *     into the forum's `deleted/` directory, so the session stops listing,
         *     stops opening, and answers `404` afterwards, while its transcript
         *     remains on disk for an operator. The browser can neither list nor
         *     restore it.
         *
         *     A session with a live runtime is stopped first, and its final snapshot
         *     carries the `session_deleted` shutdown reason. If that shutdown does not
         *     finish within the server's deletion deadline the database is left in the
         *     ordinary catalog and the request answers `409` with `session_stopping`;
         *     the shutdown may still complete, so a later delete can succeed.
         *
         *     The move never replaces a file already at the destination. That
         *     collision answers `409` with `session_delete_conflict` and leaves both
         *     the active session and the retained database untouched.
         *
         *     Deletion deliberately does not require readable session metadata, so a
         *     corrupt database can still be removed from the catalog.
         *
         *     The built-in Welcome session is process-local and cannot be deleted; it
         *     answers `404` with `not_found` without stopping its runtime.
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        /**
         * Rename a stored or live session
         * @description Replaces the session's display label. The stable session ID never
         *     changes, so existing deep links stay valid.
         *
         *     The label must be valid UTF-8, contain at most 200 Unicode code points,
         *     contain no control characters or line breaks, and have no leading or
         *     trailing Unicode whitespace. Unlike creation, an empty label has no
         *     generated-ID fallback and answers `400` with `bad_request`.
         *
         *     A session with a live runtime is renamed through its owner, so the
         *     database, the current snapshot, and every event-stream consumer observe
         *     the same label. That path also reports the owner-queue failures:
         *     `command_queue_full`, `command_timeout`, and `session_not_live`. A
         *     `command_timeout` leaves the outcome unknown, because the owner may
         *     still commit the rename after the request has given up.
         *
         *     A session without a live runtime is renamed through storage, where
         *     another process holding its lease answers `409` with `session_busy`.
         *
         *     The built-in Welcome session is process-local and cannot be renamed; it
         *     answers `404` with `not_found`.
         */
        patch: operations["renameSession"];
        trace?: never;
    };
    "/s/{forum_id}/{session_id}/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** Get the authoritative live-session snapshot */
        get: operations["getSessionSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/s/{forum_id}/{session_id}/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /**
         * Stream live-session updates
         * @description Opens the session's single allowed Server-Sent Events connection.
         *     The first record is a `snapshot` event whose JSON data is a
         *     `SessionSnapshot`. Later records are either replacement `snapshot`
         *     events or `append` events whose JSON data is an `AppendEvent`.
         *     Comment-only `: heartbeat` records keep an idle connection alive.
         *
         *     `Last-Event-ID` is ignored; reconnecting starts with a fresh snapshot.
         */
        get: operations["streamSessionEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/s/{forum_id}/{session_id}/api/v1/input": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit user input
         * @description Submits text through the session's shared input path using the fixed
         *     persona configured for the session's forum.
         */
        post: operations["submitInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/s/{forum_id}/{session_id}/api/v1/actions/stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request that generation stop */
        post: operations["stopGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/s/{forum_id}/{session_id}/api/v1/actions/default-character": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change and save the forum's default character */
        post: operations["setDefaultCharacter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example lobby */
        Identifier: string;
        EmptyObject: Record<string, never>;
        Health: {
            /** @constant */
            ready: true;
            live_session_count: number;
        };
        PersonaSummary: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            description?: string;
        };
        /**
         * @description How the browser sets this character's words, so a reader can tell one
         *     speaker from another without reading every name. A closed vocabulary:
         *     the browser owns the actual typefaces and sizes and pairs each choice
         *     with a dark-mode variant, and a workspace cannot supply styling of its
         *     own. Always present, defaults included.
         */
        CharacterAppearance: {
            /** @enum {string} */
            font: "sans" | "serif" | "mono";
            /** @enum {string} */
            style: "normal" | "italic";
            /** @enum {string} */
            weight: "normal" | "bold";
            /** @enum {string} */
            size: "small" | "normal" | "large";
        };
        CharacterSummary: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            description?: string;
            appearance: components["schemas"]["CharacterAppearance"];
        };
        ForumSummary: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            description?: string;
            default_character_id: components["schemas"]["Identifier"];
            default_persona_id: components["schemas"]["Identifier"];
            default_persona_display_name: string;
            members: components["schemas"]["CharacterSummary"][];
        };
        SessionListing: {
            id: components["schemas"]["Identifier"];
            label: string;
            live: boolean;
            updated_at: components["schemas"]["UnixTimestamp"];
        };
        RecentSession: {
            forum_id: components["schemas"]["Identifier"];
            session_id: components["schemas"]["Identifier"];
            session_label: string;
            updated_at: components["schemas"]["UnixTimestamp"];
        };
        Bootstrap: {
            initial_forum_id: components["schemas"]["Identifier"];
            initial_session_id: components["schemas"]["Identifier"];
            personas: components["schemas"]["PersonaSummary"][];
            characters: components["schemas"]["CharacterSummary"][];
            forums: components["schemas"]["ForumSummary"][];
            /** @description All sessions ordered by `updated_at` descending. */
            recent_sessions: components["schemas"]["RecentSession"][];
        };
        ProviderOption: {
            id: components["schemas"]["Identifier"];
            label: string;
        };
        StyleOption: {
            id: components["schemas"]["Identifier"];
            label: string;
            appearance: components["schemas"]["CharacterAppearance"];
        };
        CharacterDetail: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            description?: string;
            appearance: components["schemas"]["CharacterAppearance"];
            character_markdown: string;
            provider: string | null;
            style: string | null;
            available_providers: components["schemas"]["ProviderOption"][];
            available_styles: components["schemas"]["StyleOption"][];
            provider_overridden_by: string[];
            writable: boolean;
        };
        UpdateCharacterRequest: {
            provider: string | null;
            style: string | null;
        };
        PersonaDetail: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            description?: string;
            persona_markdown: string;
        };
        ForumDetail: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            description?: string;
            default_character_id: components["schemas"]["Identifier"];
            default_persona_id: components["schemas"]["Identifier"];
            default_persona_display_name: string;
            members: components["schemas"]["CharacterSummary"][];
            forum_markdown: string;
        };
        CreateSessionRequest: {
            label: string;
        };
        RenameSessionRequest: {
            label: string;
        };
        CreateSessionResult: {
            id: components["schemas"]["Identifier"];
            label: string;
        };
        SessionLabelResult: {
            id: components["schemas"]["Identifier"];
            label: string;
        };
        OpenSessionResult: {
            forum_id: components["schemas"]["Identifier"];
            session_id: components["schemas"]["Identifier"];
        };
        InputRequest: {
            /** @description Input text, limited by the server's configured prompt byte limit. */
            text: string;
        };
        SetDefaultCharacterRequest: {
            character_id: string;
        };
        CommandResult: {
            clear_input: boolean;
            notice?: string;
        };
        TranscriptEntry: {
            id: components["schemas"]["UnsignedInteger"];
            /** @enum {string} */
            kind: "human" | "character" | "notice" | "error";
            participant_id: string;
            display_name: string;
            addressed_to: string;
            addressed_to_name: string;
            text: string;
            /** @enum {string} */
            status: "complete" | "streaming" | "cancelled" | "failed";
            request_id?: components["schemas"]["UnsignedInteger"];
            /** @description Unix seconds when the entry was created; null when unknown (rows stored before schema version 3). */
            created_at: number | null;
        };
        GenerationState: {
            active: boolean;
            request_id?: components["schemas"]["UnsignedInteger"];
            character_id: string;
            character_display_name: string;
            /** @enum {string} */
            phase: "waiting" | "reasoning" | "answering" | "stopping";
            reasoning_text: string;
        };
        SessionSnapshot: {
            forum: components["schemas"]["ForumSummary"];
            session_id: components["schemas"]["Identifier"];
            session_label: string;
            characters: components["schemas"]["CharacterSummary"][];
            default_character_id: components["schemas"]["Identifier"];
            transcript: components["schemas"]["TranscriptEntry"][];
            generation: components["schemas"]["GenerationState"];
            notice?: string;
            /** @enum {string} */
            lifecycle: "starting" | "running" | "stopping";
            /** @enum {string} */
            shutdown_reason?: "browser_disconnected" | "reloading" | "session_failed" | "session_deleted" | "server_stopping";
        };
        AppendTargetEntry: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "entry";
            entry_id: components["schemas"]["UnsignedInteger"];
        };
        AppendTargetReasoning: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "reasoning";
            request_id: components["schemas"]["UnsignedInteger"];
        };
        AppendTarget: components["schemas"]["AppendTargetEntry"] | components["schemas"]["AppendTargetReasoning"];
        AppendEvent: {
            target: components["schemas"]["AppendTarget"];
            text: string;
            seq: components["schemas"]["UnsignedInteger"];
        };
        ErrorResponse: {
            error: {
                /** @enum {string} */
                code: "not_found" | "bad_request" | "body_too_large" | "prompt_too_large" | "forbidden_origin" | "internal_error" | "session_busy" | "session_stopping" | "session_limit_reached" | "session_open_timeout" | "server_stopping" | "session_not_live" | "browser_stream_in_use" | "command_timeout" | "command_queue_full" | "session_delete_conflict";
                message: string;
            };
        };
        /**
         * Format: int64
         * @description Whole seconds since the Unix epoch.
         */
        UnixTimestamp: number;
        UnsignedInteger: number;
    };
    responses: {
        /**
         * @description Content type is not JSON, or the JSON body has an invalid shape.
         *     `error.code` is `bad_request`.
         */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Origin does not match Host. `error.code` is `forbidden_origin`. */
        ForbiddenMutation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description The route identifier or selected resource was not found.
         *     `error.code` is `not_found`.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description The selected session does not have a live runtime.
         *     `error.code` is `session_not_live`.
         */
        SessionNotLive: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description The JSON request body exceeds the configured size limit.
         *     `error.code` is `body_too_large`.
         */
        BodyTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description The request failed unexpectedly.
         *     `error.code` is `internal_error`.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The client-routed application document, served as UTF-8 HTML. */
        Shell: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/html": string;
            };
        };
        /**
         * @description The command queue is full, the command timed out, or the server is
         *     stopping. `error.code` is `command_queue_full`, `command_timeout`, or
         *     `server_stopping`. On `command_timeout` the command's outcome is
         *     unknown: it may still be applied.
         */
        CommandUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Command completed at the live-session boundary. */
        CommandAccepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CommandResult"];
            };
        };
    };
    parameters: {
        /** @description Stable URL-safe forum identifier. */
        ForumId: components["schemas"]["Identifier"];
        /** @description Stable URL-safe session identifier. */
        SessionId: components["schemas"]["Identifier"];
        /** @description Stable URL-safe character identifier. */
        CharacterId: components["schemas"]["Identifier"];
        /** @description Stable URL-safe persona identifier. */
        PersonaId: components["schemas"]["Identifier"];
    };
    requestBodies: {
        EmptyJsonObject: {
            content: {
                "application/json": components["schemas"]["EmptyObject"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getShell: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Shell"];
            500: components["responses"]["InternalError"];
        };
    };
    getSessionShell: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Shell"];
            500: components["responses"]["InternalError"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is ready to accept requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bootstrap state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bootstrap"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe character identifier. */
                character_id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Character details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe character identifier. */
                character_id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCharacterRequest"];
            };
        };
        responses: {
            /** @description Character details after the write. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["ForbiddenMutation"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["BodyTooLarge"];
            500: components["responses"]["InternalError"];
        };
    };
    getPersona: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe persona identifier. */
                persona_id: components["parameters"]["PersonaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persona details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getForum: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Forum details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForumDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListing"][];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Session created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["ForbiddenMutation"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["BodyTooLarge"];
            500: components["responses"]["InternalError"];
        };
    };
    openSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["EmptyJsonObject"];
        responses: {
            /** @description Session is open. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenSessionResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["ForbiddenMutation"];
            404: components["responses"]["NotFound"];
            /**
             * @description The session is busy or stopping. `error.code` is `session_busy` when
             *     its storage lease is held by another CHA process,
             *     or `session_stopping` while its previous runtime is still shutting
             *     down. Both are retryable.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            413: components["responses"]["BodyTooLarge"];
            500: components["responses"]["InternalError"];
            /**
             * @description Session limit, open timeout, or server shutdown prevented opening.
             *     `error.code` is `session_limit_reached`, `session_open_timeout`, or
             *     `server_stopping`. On `session_open_timeout` the session may still
             *     finish opening, so the request can be retried.
             */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["EmptyJsonObject"];
        responses: {
            /** @description Session moved to deleted storage. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["ForbiddenMutation"];
            404: components["responses"]["NotFound"];
            /** @description Session is busy, stopping, or its archive destination exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            413: components["responses"]["BodyTooLarge"];
            500: components["responses"]["InternalError"];
            /** @description Server shutdown prevented deletion. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    renameSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameSessionRequest"];
            };
        };
        responses: {
            /** @description Session renamed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionLabelResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["ForbiddenMutation"];
            404: components["responses"]["NotFound"];
            /** @description Session is busy or no longer live. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            413: components["responses"]["BodyTooLarge"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["CommandUnavailable"];
        };
    };
    getSessionSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["SessionNotLive"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["CommandUnavailable"];
        };
    };
    streamSessionEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description SSE stream containing `snapshot` and `append` events. Event data is
             *     one compact JSON value on the `data:` line.
             */
            200: {
                headers: {
                    "Cache-Control"?: "no-cache";
                    "X-Accel-Buffering"?: "no";
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
            /**
             * @description Session is not live or already has an event stream. `error.code` is
             *     `session_not_live`, or `browser_stream_in_use` when the session's one
             *     allowed connection is already held by another browser page.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
            503: components["responses"]["CommandUnavailable"];
        };
    };
    submitInput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InputRequest"];
            };
        };
        responses: {
            200: components["responses"]["CommandAccepted"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["ForbiddenMutation"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["SessionNotLive"];
            /**
             * @description Request body or prompt text exceeds its configured limit.
             *     `error.code` is `body_too_large` for the whole request body, or
             *     `prompt_too_large` for the `text` field alone.
             */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
            503: components["responses"]["CommandUnavailable"];
        };
    };
    stopGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["EmptyJsonObject"];
        responses: {
            200: components["responses"]["CommandAccepted"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["ForbiddenMutation"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["SessionNotLive"];
            413: components["responses"]["BodyTooLarge"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["CommandUnavailable"];
        };
    };
    setDefaultCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable URL-safe forum identifier. */
                forum_id: components["parameters"]["ForumId"];
                /** @description Stable URL-safe session identifier. */
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDefaultCharacterRequest"];
            };
        };
        responses: {
            200: components["responses"]["CommandAccepted"];
            400: components["responses"]["BadRequest"];
            403: components["responses"]["ForbiddenMutation"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["SessionNotLive"];
            413: components["responses"]["BodyTooLarge"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["CommandUnavailable"];
        };
    };
}
