/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example lobby */
        Identifier: string;
        EmptyObject: Record<string, never>;
        OpenAiAuth: {
            /** @enum {string} */
            status: "signed_out" | "waiting" | "connected";
            /**
             * @description Present only while `status` is `waiting`. The code the user enters
             *     at the verification URL.
             */
            user_code?: string;
            /**
             * Format: uri
             * @description Present only while `status` is `waiting`. Always
             *     `https://auth.openai.com/codex/device`.
             */
            verification_url?: string;
            /**
             * @description Present only while `status` is `waiting`. Unix seconds when this
             *     pending login expires. The browser can compare with `Date.now()/1000`.
             */
            attempt_expires_at?: components["schemas"]["UnixTimestamp"];
            /**
             * @description Present only while `status` is `waiting`. Milliseconds until the
             *     next eligible `POST /api/v1/openai/auth/poll`. The browser can pass
             *     this value to `setTimeout`.
             */
            next_poll_delay_ms?: number;
            /**
             * @description Sanitized operator-facing message when the last owner operation
             *     failed. Omitted when there is no such message.
             */
            error?: string;
        };
        Health: {
            /** @constant */
            ready: true;
            live_session_count: number;
        };
        PersonaSummary: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            description?: string;
            appearance: components["schemas"]["CharacterAppearance"];
            voice?: components["schemas"]["SpeechVoice"];
        };
        /**
         * @description How the browser sets this character's words, so a reader can tell one
         *     speaker from another without reading every name. A closed vocabulary:
         *     the browser owns the actual typefaces, sizes, and colors and pairs each choice
         *     with a dark-mode variant, and a workspace cannot supply styling of its
         *     own. Always present, defaults included.
         */
        CharacterAppearance: {
            /** @enum {string} */
            font: "sans" | "serif" | "mono";
            /** @enum {string} */
            style: "normal" | "italic";
            /** @enum {string} */
            weight: "light" | "normal" | "medium" | "semibold" | "bold";
            /** @enum {string} */
            size: "small" | "normal" | "large";
            /** @enum {string} */
            text_color: "normal" | "muted" | "accent";
        };
        SpeechVoiceSettings: {
            speed?: number;
        };
        SpeechVoice: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            /** @description FishAudio reference ID; field name retained for compatibility. */
            elevenlabs_voice_id: string;
            settings: components["schemas"]["SpeechVoiceSettings"];
        };
        CharacterSummary: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            description?: string;
            appearance: components["schemas"]["CharacterAppearance"];
            voice?: components["schemas"]["SpeechVoice"];
        };
        ForumSummary: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            description?: string;
            default_character_id: components["schemas"]["Identifier"];
            default_persona_id: components["schemas"]["Identifier"];
            default_persona_display_name: string;
            members: components["schemas"]["CharacterSummary"][];
        };
        SessionListing: {
            id: components["schemas"]["Identifier"];
            label: string;
            live: boolean;
            updated_at: components["schemas"]["UnixTimestamp"];
        };
        RecentSession: {
            forum_id: components["schemas"]["Identifier"];
            session_id: components["schemas"]["Identifier"];
            session_label: string;
            updated_at: components["schemas"]["UnixTimestamp"];
        };
        VaultSwitchRequest: {
            vault_name: string;
            password: string | null;
        };
        MergeVaultRequest: {
            source_vault: string;
            password: string | null;
        };
        VaultDetail: {
            display_name: string;
            protected: boolean;
            data_path: string;
            /** @description Absolute mirror directory path. */
            mirror_path: string | null;
            /** @description Absolute editable-workspace directory path. */
            modify_path: string | null;
            active: boolean;
            can_delete: boolean;
        };
        CreateVaultRequest: {
            display_name: string;
            copy_from: string | null;
            password: string | null;
        };
        DownloadR2VaultRequest: {
            name: string;
        };
        UpdateVaultRequest: {
            vault_name: string;
            display_name: string;
            password: string | null;
        };
        DeleteVaultRequest: {
            vault_name: string;
        };
        Bootstrap: {
            vault_name: string;
            vaults: string[];
            initial_forum_id: components["schemas"]["Identifier"];
            initial_session_id: components["schemas"]["Identifier"];
            entrance_forum_id: components["schemas"]["Identifier"];
            personas: components["schemas"]["PersonaSummary"][];
            characters: components["schemas"]["CharacterSummary"][];
            forums: components["schemas"]["ForumSummary"][];
            /** @description All sessions ordered by `updated_at` descending. */
            recent_sessions: components["schemas"]["RecentSession"][];
        };
        ProviderOption: {
            id: components["schemas"]["Identifier"];
            label: string;
        };
        ProviderSummary: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            model: string;
            host: string;
        };
        CreateProviderRequest: {
            display_name: string;
            /** @description Existing provider ID whose settings should be copied. */
            copy_from: string | null;
        };
        ProviderUpdate: {
            display_name: string;
            host: string;
            port: number;
            base_path: string;
            /** @enum {string} */
            mode: "net" | "test";
            model: string;
            stream: boolean;
            temperature: number | null;
            max_tokens: number | null;
            timeout_s: number;
            idle_timeout_s: number;
            api_key: string | null;
            /** @enum {string} */
            reasoning_effort: "none" | "minimal" | "low" | "medium" | "high" | "xhigh";
            /** @enum {string} */
            reasoning_format: "auto" | "none" | "reasoning_content" | "reasoning";
            https: boolean;
            /** @enum {string} */
            api: "chat_completions" | "responses";
            /** @enum {string} */
            auth: "none" | "openai_subscription";
            /** @enum {string} */
            web_search: "off" | "auto" | "required";
            /** @enum {string} */
            cache_retention: "off" | "short" | "long";
            openrouter_targets?: string[];
        };
        ProviderDetail: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            host: string;
            port: number;
            base_path: string;
            /** @enum {string} */
            mode: "net" | "test";
            model: string;
            stream: boolean;
            temperature: number | null;
            max_tokens: number | null;
            timeout_s: number;
            idle_timeout_s: number;
            api_key: string | null;
            /** @enum {string} */
            reasoning_effort: "none" | "minimal" | "low" | "medium" | "high" | "xhigh";
            /** @enum {string} */
            reasoning_format: "auto" | "none" | "reasoning_content" | "reasoning";
            https: boolean;
            /** @enum {string} */
            api: "chat_completions" | "responses";
            /** @enum {string} */
            auth: "none" | "openai_subscription";
            /** @enum {string} */
            web_search: "off" | "auto" | "required";
            /** @enum {string} */
            cache_retention: "off" | "short" | "long";
            openrouter_targets: string[];
            writable: boolean;
            used_by: string[];
        };
        StyleUpdate: {
            display_name: string;
            /** @enum {string} */
            font: "sans" | "serif" | "mono";
            /** @enum {string} */
            style: "normal" | "italic";
            /** @enum {string} */
            weight: "light" | "normal" | "medium" | "semibold" | "bold";
            /** @enum {string} */
            size: "small" | "normal" | "large";
            /** @enum {string} */
            text_color: "normal" | "muted" | "accent";
        };
        CreateStyleRequest: {
            display_name: string;
        };
        StyleDetail: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            /** @enum {string} */
            font: "sans" | "serif" | "mono";
            /** @enum {string} */
            style: "normal" | "italic";
            /** @enum {string} */
            weight: "light" | "normal" | "medium" | "semibold" | "bold";
            /** @enum {string} */
            size: "small" | "normal" | "large";
            /** @enum {string} */
            text_color: "normal" | "muted" | "accent";
            writable: boolean;
            used_by: string[];
        };
        VoiceUpdate: {
            display_name: string;
            description: string;
            /** @description FishAudio reference ID; field name retained for compatibility. */
            elevenlabs_voice_id: string;
            speed: number | null;
        };
        CreateVoiceRequest: {
            display_name: string;
            description: string;
            /** @description FishAudio reference ID; field name retained for compatibility. */
            elevenlabs_voice_id: string;
        };
        VoiceDetail: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            description: string;
            /** @description FishAudio reference ID; field name retained for compatibility. */
            elevenlabs_voice_id: string;
            speed: number | null;
            writable: boolean;
            used_by: string[];
        };
        JevSettings: {
            url: string;
            model: string;
            api_key: components["schemas"]["Identifier"];
        };
        WebSearchSettings: {
            enabled: boolean;
            /** @enum {string} */
            provider: "brave" | "tavily";
            api_key: string;
            query_provider: string;
        };
        VoiceInputSettings: {
            /** @enum {string} */
            provider: "openai" | "xai";
            url: string;
            model: string;
            api_key: components["schemas"]["Identifier"];
            /** @enum {string} */
            delay: "low" | "medium" | "high" | "xhigh";
            prompt: string;
            send_phrase: string;
        };
        VoiceInputRuntime: {
            /** @enum {string} */
            provider: "openai" | "xai";
            url: string;
            model: string;
            /** @enum {string} */
            delay: "low" | "medium" | "high" | "xhigh";
            prompt: string;
            send_phrase: string;
        };
        XaiVoiceStartResult: {
            session_id: string;
            stop_budget_ms: number;
        };
        XaiVoicePieces: {
            session_id: string;
            pieces: string[];
            preview?: string;
        };
        VoiceOutputSettings: {
            url: string;
            model: string;
            api_key: components["schemas"]["Identifier"];
            output_format: string;
            default_voice: string;
        };
        VoiceOutputRuntime: {
            url: string;
            model: string;
            output_format: string;
            default_voice_id: string;
        };
        ApiKeyDetail: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            has_value: boolean;
            used_by: string[];
        };
        CreateApiKeyRequest: {
            display_name: string;
            value: string;
        };
        RenameApiKeyRequest: {
            display_name: string;
        };
        ReplaceApiKeyValueRequest: {
            value: string;
        };
        R2StorageDetail: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            url: string;
            access_key_id: string;
            has_secret_key: boolean;
        };
        SaveR2StorageRequest: {
            display_name: string;
            url: string;
            access_key_id: string;
            /** @description Null keeps the existing secret key; creating requires a value. */
            secret_key: string | null;
        };
        StyleOption: {
            id: components["schemas"]["Identifier"];
            label: string;
            appearance: components["schemas"]["CharacterAppearance"];
        };
        VoiceOption: {
            id: components["schemas"]["Identifier"];
            label: string;
        };
        CharacterDetail: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            description?: string;
            appearance: components["schemas"]["CharacterAppearance"];
            voice?: components["schemas"]["SpeechVoice"];
            /** @description Template-expanded Markdown used for display. */
            character_markdown: string;
            /** @description Verbatim Markdown accepted by the definition editor. */
            editable_markdown: string;
            /** @description Sorted filenames directly in the character directory, without content. */
            markdown_files: string[];
            provider: string | null;
            style: string | null;
            voice_id: string | null;
            /** @enum {string|null} */
            reasoning_effort: "none" | "minimal" | "low" | "medium" | "high" | "xhigh" | null;
            /** @enum {string|null} */
            web_search: "off" | "auto" | "required" | null;
            available_providers: components["schemas"]["ProviderOption"][];
            available_styles: components["schemas"]["StyleOption"][];
            available_voices: components["schemas"]["VoiceOption"][];
            /** @description Whether model, style, and voice settings can be changed. */
            settings_writable: boolean;
            /** @description Whether the name and definition can be changed and the character deleted. */
            writable: boolean;
        };
        MarkdownFile: {
            filename: string;
            /** @description Verbatim file content, preserving template expressions. */
            content: string;
            writable: boolean;
        };
        CreateMarkdownFileRequest: {
            filename: string;
            content: string;
        };
        UpdateMarkdownFileRequest: {
            content: string;
        };
        CreateCharacterRequest: {
            display_name: string;
            description: string;
        };
        UpdateCharacterRequest: {
            provider: string;
            style: string | null;
            voice_id: string | null;
            /** @enum {string|null} */
            reasoning_effort: "none" | "minimal" | "low" | "medium" | "high" | "xhigh" | null;
            /** @enum {string|null} */
            web_search: "off" | "auto" | "required" | null;
        };
        UpdateCharacterDefinitionRequest: {
            display_name?: string;
            character_markdown?: string;
        };
        PersonaDetail: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            description?: string;
            appearance: components["schemas"]["CharacterAppearance"];
            voice?: components["schemas"]["SpeechVoice"];
            persona_markdown: string;
            style: string | null;
            voice_id: string | null;
            available_styles: components["schemas"]["StyleOption"][];
            available_voices: components["schemas"]["VoiceOption"][];
            writable: boolean;
        };
        UpdatePersonaRequest: {
            display_name?: string;
            persona_markdown?: string;
            style?: string | null;
            voice_id?: string | null;
        };
        CreatePersonaRequest: {
            display_name: string;
        };
        ForumDetail: {
            id: components["schemas"]["Identifier"];
            display_name: string;
            description?: string;
            default_character_id: components["schemas"]["Identifier"];
            default_persona_id: components["schemas"]["Identifier"];
            default_persona_display_name: string;
            members: components["schemas"]["CharacterSummary"][];
            forum_markdown: string;
            markdown_files: string[];
            writable: boolean;
        };
        CreateForumRequest: {
            display_name: string;
            persona_id: components["schemas"]["Identifier"];
        };
        UpdateForumRequest: {
            display_name?: string;
            forum_markdown?: string;
        };
        UpdateForumMembersRequest: {
            character_ids: components["schemas"]["Identifier"][];
            persona_id: components["schemas"]["Identifier"];
        };
        CreateSessionRequest: {
            label: string;
        };
        RenameSessionRequest: {
            label: string;
        };
        CreateSessionResult: {
            id: components["schemas"]["Identifier"];
            label: string;
        };
        SessionLabelResult: {
            id: components["schemas"]["Identifier"];
            label: string;
        };
        OpenSessionResult: {
            forum_id: components["schemas"]["Identifier"];
            session_id: components["schemas"]["Identifier"];
        };
        InputRequest: {
            /** @description Input text, limited by the server's configured prompt byte limit. */
            text: string;
        };
        CoverRequest: {
            through_entry_id: number;
        };
        DeleteTurnRequest: {
            response_entry_id: number;
        };
        SetDefaultCharacterRequest: {
            character_id: string;
        };
        CommandResult: {
            clear_input: boolean;
            notice?: string;
        };
        TranscriptEntry: {
            id: components["schemas"]["UnsignedInteger"];
            /** @enum {string} */
            kind: "human" | "character" | "notice" | "error";
            participant_id: string;
            display_name: string;
            addressed_to: string;
            addressed_to_name: string;
            text: string;
            /** @enum {string} */
            status: "complete" | "streaming" | "cancelled" | "failed";
            request_id?: components["schemas"]["UnsignedInteger"];
            /** @description Unix seconds when the entry was created; null when unknown. */
            created_at: number | null;
            /** @description Provider-reported input tokens for this response; null when unavailable. */
            input_tokens?: number | null;
            /** @description Provider-reported output tokens for this response; null when unavailable. */
            output_tokens?: number | null;
            /** @description Whether this response request included web search data. */
            web_search_used?: boolean;
            /** @description Whether saved audio is available for this entry. */
            has_cached_audio?: boolean;
        };
        GenerationState: {
            active: boolean;
            request_id?: components["schemas"]["UnsignedInteger"];
            character_id: string;
            character_display_name: string;
            /** @enum {string} */
            phase: "waiting" | "reasoning" | "answering" | "stopping";
            reasoning_text: string;
        };
        SessionSnapshot: {
            forum: components["schemas"]["ForumSummary"];
            session_id: components["schemas"]["Identifier"];
            session_label: string;
            characters: components["schemas"]["CharacterSummary"][];
            default_character_id: components["schemas"]["Identifier"] | "*";
            transcript: components["schemas"]["TranscriptEntry"][];
            covered_until?: components["schemas"]["UnsignedInteger"];
            generation: components["schemas"]["GenerationState"];
            notice?: string;
            /** @enum {string} */
            lifecycle: "starting" | "running" | "stopping";
            /** @enum {string} */
            shutdown_reason?: "session_closed" | "reloading" | "session_failed" | "session_deleted" | "server_stopping";
        };
        AppendTargetEntry: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "entry";
            entry_id: components["schemas"]["UnsignedInteger"];
        };
        AppendTargetReasoning: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "reasoning";
            request_id: components["schemas"]["UnsignedInteger"];
        };
        AppendTarget: components["schemas"]["AppendTargetEntry"] | components["schemas"]["AppendTargetReasoning"];
        AppendEvent: {
            target: components["schemas"]["AppendTarget"];
            text: string;
            seq: components["schemas"]["UnsignedInteger"];
        };
        AudioDownloadRequest: {
            vault_name: string;
            reference_id: string;
            settings?: {
                speed?: number;
            };
        };
        AudioDownloadBatchEntry: {
            entry_id: number;
            reference_id: string;
            settings?: {
                speed?: number;
            };
        };
        AudioDownloadBatchRequest: {
            vault_name: string;
            /** @description Entry IDs must be unique within the batch. */
            entries: components["schemas"]["AudioDownloadBatchEntry"][];
        };
        AudioDownloadBatchAcceptance: {
            entries: components["schemas"]["AudioDownloadAcceptance"][];
        };
        AudioDownloadAcceptance: {
            entry_id: number;
            cached: boolean;
            /** @enum {string} */
            state?: "queued" | "running";
        };
        AudioDownloadJob: {
            entry_id: number;
            /** @enum {string} */
            state: "queued" | "running" | "failed";
            error?: string;
        };
        AudioDownloadStatus: {
            cached_entry_ids: number[];
            downloads: components["schemas"]["AudioDownloadJob"][];
        };
        ErrorResponse: {
            error: {
                /** @enum {string} */
                code: "not_found" | "body_too_large" | "prompt_too_large" | "internal_error" | "speech_busy" | "vault_changed" | "session_stopping" | "session_limit_reached" | "session_open_timeout" | "server_stopping" | "session_not_live" | "command_timeout" | "command_queue_full" | "vault_password_required" | "source_vault_password_required" | "invalid_argument" | "operation_cancelled" | "application_unavailable";
                message: string;
            };
        };
        NativeSafeInteger: number;
        BridgeInfo: {
            /** @enum {integer} */
            protocol_version: 1;
            application_version: string;
            platform: string;
        };
        NativeRequest: {
            connection_id: string;
            id: components["schemas"]["NativeSafeInteger"];
            context_epoch: components["schemas"]["NativeSafeInteger"];
            method: string;
            params?: {
                [key: string]: unknown;
            };
        };
        NativeReply: {
            connection_id: string;
            id: components["schemas"]["NativeSafeInteger"];
            context_epoch: components["schemas"]["NativeSafeInteger"];
            ok: boolean;
            result?: unknown;
            error?: {
                code: string;
                message: string;
            };
        };
        NativeSessionEvent: {
            connection_id: string;
            context_epoch: components["schemas"]["NativeSafeInteger"];
            subscription_id: string;
            /** @enum {string} */
            event: "session.snapshot" | "session.append";
            forum_id: string;
            session_id: string;
            seq: components["schemas"]["NativeSafeInteger"];
            payload: unknown;
        };
        NativeDeliveryBatch: {
            connection_id: string;
            delivery_id: components["schemas"]["NativeSafeInteger"];
            messages: unknown[];
        };
        NativeDeliveryAck: {
            connection_id: string;
            delivery_id: components["schemas"]["NativeSafeInteger"];
        };
        MediaResource: {
            resource_id: string;
            url: string;
            mime_type: string;
            byte_length: components["schemas"]["NativeSafeInteger"];
            streaming?: boolean;
        };
        /**
         * Format: int64
         * @description Whole seconds since the Unix epoch.
         */
        UnixTimestamp: number;
        UnsignedInteger: number;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
