map_hash_bucket_size 128;

map $http_authorization $cha_user {
    include /etc/nginx/cha-users.map;
    default "";
}

server {
    listen @CHA_LISTEN@;
    server_name _;

    location /v1/ {
        if ($cha_user = "") { return 401; }
        client_max_body_size      16m;
        include                   scgi_params;
        scgi_pass                 unix:/run/cha/$cha_user.sock;
        scgi_pass_request_headers off;
        scgi_buffering            off;
        scgi_read_timeout         3600s;
        scgi_send_timeout         3600s;
    }
}
