import Foundation
import WebKit

private let chaMessageHandlerName = "cha"

func nativeBootstrapJavaScript(connectionId: String) -> String {
    // connectionId is generated by native code (view-N), never user content.
    """
    window.__CHA_NATIVE_CONNECTION_ID__ = "\(connectionId)";
    window.__CHA_NATIVE_CONTEXT_EPOCH__ = 0;
    window.__CHA_NATIVE_QUEUE__ = window.__CHA_NATIVE_QUEUE__ || [];
    if (typeof window.__CHA_NATIVE_RECEIVE__ !== "function") {
      window.__CHA_NATIVE_RECEIVE__ = function(batch) {
        window.__CHA_NATIVE_QUEUE__.push(batch);
      };
    }
    window.__CHA_NATIVE_POST__ = function(message) {
      if (window.webkit && window.webkit.messageHandlers
          && window.webkit.messageHandlers.cha) {
        window.webkit.messageHandlers.cha.postMessage(message);
      }
    };
    window.__CHA_NATIVE_SAVE_PENDING__ = {};
    window.__CHA_NATIVE_SAVE_SEQ__ = 0;
    window.__CHA_NATIVE_SAVE_SESSION__ = function(suggestedName, forumId, sessionId) {
      return new Promise(function(resolve, reject) {
        var id = String(++window.__CHA_NATIVE_SAVE_SEQ__);
        window.__CHA_NATIVE_SAVE_PENDING__[id] = {resolve: resolve, reject: reject};
        window.__CHA_NATIVE_POST__(JSON.stringify({
          native_action: "save_session",
          id: id,
          connection_id: window.__CHA_NATIVE_CONNECTION_ID__,
          context_epoch: window.__CHA_NATIVE_CONTEXT_EPOCH__,
          suggested_name: suggestedName,
          forum_id: forumId,
          session_id: sessionId
        }));
      });
    };
    window.__CHA_NATIVE_SAVE_DONE__ = function(id, ok, message) {
      var pending = window.__CHA_NATIVE_SAVE_PENDING__[id];
      if (!pending) return;
      delete window.__CHA_NATIVE_SAVE_PENDING__[id];
      if (ok) pending.resolve();
      else pending.reject(new Error(message || "Save failed"));
    };
    """
}

func nativeBootstrapUserScript(connectionId: String) -> WKUserScript {
    WKUserScript(
        source: nativeBootstrapJavaScript(connectionId: connectionId),
        injectionTime: .atDocumentStart,
        forMainFrameOnly: true)
}

func makeNativeWebViewConfiguration(assetRoot: URL) -> (
    WKWebViewConfiguration, ChaAssetSchemeHandler
) {
    let configuration = WKWebViewConfiguration()
    configuration.mediaTypesRequiringUserActionForPlayback = []
    let handler = ChaAssetSchemeHandler(root: assetRoot)
    configuration.setURLSchemeHandler(handler, forURLScheme: chaAssetScheme)
    return (configuration, handler)
}

func isSameDocumentHashChange(from current: URL?, to next: URL?) -> Bool {
    guard let current, let next, current.fragment != next.fragment,
          var from = URLComponents(url: current, resolvingAgainstBaseURL: false),
          var to = URLComponents(url: next, resolvingAgainstBaseURL: false) else { return false }
    from.fragment = nil
    to.fragment = nil
    return from == to
}

final class ChaNativeDeliveryBox: @unchecked Sendable {
    weak var owner: ChaNativeBridgeReceiver?
}

private func chaDeliveryTrampoline(
    _ context: UnsafeMutableRawPointer?,
    _ connection: UnsafePointer<CChar>?,
    _ json: UnsafePointer<CChar>?
) {
    guard let context, let connection, let json else { return }
    let box = Unmanaged<ChaNativeDeliveryBox>.fromOpaque(context).takeUnretainedValue()
    let connectionId = String(cString: connection)
    let payload = String(cString: json)
    DispatchQueue.main.async {
        box.owner?.deliver(connectionId: connectionId, json: payload)
    }
}

final class ChaNativeBridgeReceiver: NSObject, WKScriptMessageHandler {
    private let runtime: OpaquePointer
    private let deliveryBox = ChaNativeDeliveryBox()
    private var retainedDeliveryContext: UnsafeMutableRawPointer?
    private weak var webView: WKWebView?
    private(set) var connectionId: String?
    var isTrustedOrigin: ((WKSecurityOrigin) -> Bool) = { origin in
        isChaAssetOrigin(origin)
    }
    var saveSession: ((String, String, UInt64, String, String, String) -> Void)?

    init(runtime: OpaquePointer) {
        self.runtime = runtime
        super.init()
        deliveryBox.owner = self
    }

    deinit {
        if retainedDeliveryContext != nil {
            clearDeliveryCallback()
        }
    }

    func attach(to webView: WKWebView, mediaHandler: ChaAssetSchemeHandler? = nil) {
        self.webView = webView
        webView.configuration.userContentController.add(
            self, name: chaMessageHandlerName)
        if let mediaHandler {
            mediaHandler.readMedia = { [weak self] id in
                self?.readMedia(id)
            }
            mediaHandler.readMediaChunk = { [weak self] id, offset in
                self?.readMediaChunk(id, offset: offset) ?? (404, "text/plain", Data(), false)
            }
        }
        installDeliveryCallback()
        prepareDocumentReplacement()
    }

    private func readMedia(_ resourceId: String) -> (type: String, body: Data)? {
        guard let connectionId else { return nil }
        var mime: UnsafeMutablePointer<CChar>?
        var bytes: UnsafeMutableRawPointer?
        var size: UInt64 = 0
        var error: UnsafeMutablePointer<CChar>?
        let ok = connectionId.withCString { connection in
            resourceId.withCString { resource in
                cha_runtime_read_resource(
                    runtime, connection, resource, &mime, &bytes, &size, &error)
            }
        }
        cha_string_free(error)
        defer {
            cha_string_free(mime)
            cha_bytes_free(bytes)
        }
        guard ok != 0, let bytes else { return nil }
        let type = mime.map { String(cString: $0) } ?? "application/octet-stream"
        let body = Data(bytes: bytes, count: Int(size))
        return (type, body)
    }

    private func readMediaChunk(_ resourceId: String, offset: UInt64) -> (status: Int, type: String, body: Data, complete: Bool) {
        guard let connectionId else { return (404, "text/plain", Data(), false) }
        var mime: UnsafeMutablePointer<CChar>?
        var bytes: UnsafeMutableRawPointer?
        var size: UInt64 = 0
        var complete: Int32 = 0
        let status = connectionId.withCString { connection in
            resourceId.withCString { resource in
                cha_runtime_read_resource_chunk(runtime, connection, resource, offset, &mime, &bytes, &size, &complete)
            }
        }
        defer { cha_string_free(mime); cha_bytes_free(bytes) }
        return (Int(status), mime.map { String(cString: $0) } ?? "application/octet-stream",
                bytes.map { Data(bytes: $0, count: Int(size)) } ?? Data(), complete != 0)
    }

    func detach() {
        if let connectionId {
            cha_runtime_close_connection(runtime, connectionId)
            self.connectionId = nil
        }
        clearDeliveryCallback()
        webView?.configuration.userContentController
            .removeScriptMessageHandler(forName: chaMessageHandlerName)
        webView = nil
    }

    private func installDeliveryCallback() {
        clearDeliveryCallback()
        let context = Unmanaged.passRetained(deliveryBox).toOpaque()
        retainedDeliveryContext = context
        cha_runtime_set_delivery_callback(
            runtime, chaDeliveryTrampoline, context)
    }

    private func clearDeliveryCallback() {
        cha_runtime_set_delivery_callback(runtime, nil, nil)
        if let context = retainedDeliveryContext {
            retainedDeliveryContext = nil
            Unmanaged<ChaNativeDeliveryBox>.fromOpaque(context).release()
        }
    }

    @discardableResult
    func prepareDocumentReplacement() -> String? {
        if let connectionId {
            cha_runtime_close_connection(runtime, connectionId)
            self.connectionId = nil
        }
        var error: UnsafeMutablePointer<CChar>?
        guard let opened = cha_runtime_open_connection(runtime, &error) else {
            cha_string_free(error)
            return nil
        }
        let id = String(cString: opened)
        cha_string_free(opened)
        connectionId = id
        guard let controller = webView?.configuration.userContentController else {
            return id
        }
        controller.removeAllUserScripts()
        controller.addUserScript(nativeBootstrapUserScript(connectionId: id))
        return id
    }

    func willNavigate(_ navigation: WKNavigationAction, in view: WKWebView) {
        if navigation.targetFrame?.isMainFrame == true
            && !isSameDocumentHashChange(from: view.url, to: navigation.request.url) {
            prepareDocumentReplacement()
        }
    }

    func userContentController(
        _ userContentController: WKUserContentController,
        didReceive message: WKScriptMessage
    ) {
        guard message.name == chaMessageHandlerName,
              message.frameInfo.isMainFrame,
              isTrustedOrigin(message.frameInfo.securityOrigin),
              let connectionId,
              let body = message.body as? String else {
            return
        }
        if let data = body.data(using: .utf8),
           let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
           object["native_action"] != nil {
            guard object["native_action"] as? String == "save_session",
                  let id = object["id"] as? String,
                  let originatingConnection = object["connection_id"] as? String,
                  originatingConnection == connectionId,
                  let epochNumber = object["context_epoch"] as? NSNumber,
                  CFGetTypeID(epochNumber) != CFBooleanGetTypeID(),
                  epochNumber.doubleValue >= 1,
                  epochNumber.doubleValue <= 9_007_199_254_740_991,
                  let contextEpoch = UInt64(exactly: epochNumber.doubleValue),
                  let forumId = object["forum_id"] as? String,
                  let sessionId = object["session_id"] as? String else {
                return
            }
            saveSession?(
                originatingConnection,
                id,
                contextEpoch,
                object["suggested_name"] as? String ?? "session.md",
                forumId,
                sessionId)
            return
        }
        connectionId.withCString { connection in
            body.withCString { json in
                cha_runtime_handle_message(runtime, connection, json)
            }
        }
    }

    func completeSave(
        connectionId: String,
        id: String,
        ok: Bool,
        message: String
    ) {
        guard connectionId == self.connectionId, let webView else { return }
        webView.callAsyncJavaScript(
            """
            if (typeof window.__CHA_NATIVE_SAVE_DONE__ === "function") {
              window.__CHA_NATIVE_SAVE_DONE__(id, ok, message);
            }
            """,
            arguments: ["id": id, "ok": ok, "message": message],
            in: nil,
            in: .page,
            completionHandler: { _ in })
    }

    func deliver(connectionId: String, json: String) {
        guard connectionId == self.connectionId, let webView else { return }
        guard let data = json.data(using: .utf8),
              let batch = try? JSONSerialization.jsonObject(with: data) else {
            return
        }
        webView.callAsyncJavaScript(
            """
            if (typeof window.__CHA_NATIVE_RECEIVE__ === "function") {
              window.__CHA_NATIVE_RECEIVE__(batch);
            } else {
              (window.__CHA_NATIVE_QUEUE__ = window.__CHA_NATIVE_QUEUE__ || []).push(batch);
            }
            """,
            arguments: ["batch": batch],
            in: nil,
            in: .page,
            completionHandler: { _ in })
    }
}
