import Foundation
import WebKit

private let chaMessageHandlerName = "cha"

func nativeBootstrapJavaScript(connectionId: String) -> String {
    // connectionId is generated by native code (view-N), never user content.
    """
    window.__CHA_NATIVE_CONNECTION_ID__ = "\(connectionId)";
    window.__CHA_NATIVE_QUEUE__ = window.__CHA_NATIVE_QUEUE__ || [];
    if (typeof window.__CHA_NATIVE_RECEIVE__ !== "function") {
      window.__CHA_NATIVE_RECEIVE__ = function(batch) {
        window.__CHA_NATIVE_QUEUE__.push(batch);
      };
    }
    window.__CHA_NATIVE_POST__ = function(message) {
      if (window.webkit && window.webkit.messageHandlers
          && window.webkit.messageHandlers.cha) {
        window.webkit.messageHandlers.cha.postMessage(message);
      }
    };
    """
}

func nativeBootstrapUserScript(connectionId: String) -> WKUserScript {
    WKUserScript(
        source: nativeBootstrapJavaScript(connectionId: connectionId),
        injectionTime: .atDocumentStart,
        forMainFrameOnly: true)
}

func makeNativeWebViewConfiguration(assetRoot: URL) -> (
    WKWebViewConfiguration, ChaAssetSchemeHandler
) {
    let configuration = WKWebViewConfiguration()
    configuration.mediaTypesRequiringUserActionForPlayback = []
    let handler = ChaAssetSchemeHandler(root: assetRoot)
    configuration.setURLSchemeHandler(handler, forURLScheme: chaAssetScheme)
    return (configuration, handler)
}

func isSameDocumentHashChange(from current: URL?, to next: URL?) -> Bool {
    guard let current, let next else { return false }
    return current.scheme?.caseInsensitiveCompare(next.scheme ?? "") == .orderedSame
        && current.host?.caseInsensitiveCompare(next.host ?? "") == .orderedSame
        && current.path == next.path
        && current.fragment != next.fragment
}

final class ChaNativeDeliveryBox: @unchecked Sendable {
    weak var owner: ChaNativeBridgeReceiver?
}

private func chaDeliveryTrampoline(
    _ context: UnsafeMutableRawPointer?,
    _ connection: UnsafePointer<CChar>?,
    _ json: UnsafePointer<CChar>?
) {
    guard let context, let connection, let json else { return }
    let box = Unmanaged<ChaNativeDeliveryBox>.fromOpaque(context).takeUnretainedValue()
    let connectionId = String(cString: connection)
    let payload = String(cString: json)
    DispatchQueue.main.async {
        box.owner?.deliver(connectionId: connectionId, json: payload)
    }
}

final class ChaNativeBridgeReceiver: NSObject, WKScriptMessageHandler {
    private let runtime: OpaquePointer
    private let deliveryBox = ChaNativeDeliveryBox()
    private var retainedDeliveryContext: UnsafeMutableRawPointer?
    private weak var webView: WKWebView?
    private(set) var connectionId: String?
    var isTrustedOrigin: ((WKSecurityOrigin) -> Bool) = { origin in
        isChaAssetOrigin(origin)
    }

    init(runtime: OpaquePointer) {
        self.runtime = runtime
        super.init()
        deliveryBox.owner = self
    }

    deinit {
        if retainedDeliveryContext != nil {
            clearDeliveryCallback()
        }
    }

    func attach(to webView: WKWebView) {
        self.webView = webView
        webView.configuration.userContentController.add(
            self, name: chaMessageHandlerName)
        installDeliveryCallback()
        prepareDocumentReplacement()
    }

    func detach() {
        if let connectionId {
            cha_runtime_close_connection(runtime, connectionId)
            self.connectionId = nil
        }
        clearDeliveryCallback()
        webView?.configuration.userContentController
            .removeScriptMessageHandler(forName: chaMessageHandlerName)
        webView = nil
    }

    private func installDeliveryCallback() {
        clearDeliveryCallback()
        let context = Unmanaged.passRetained(deliveryBox).toOpaque()
        retainedDeliveryContext = context
        cha_runtime_set_delivery_callback(
            runtime, chaDeliveryTrampoline, context)
    }

    private func clearDeliveryCallback() {
        cha_runtime_set_delivery_callback(runtime, nil, nil)
        if let context = retainedDeliveryContext {
            retainedDeliveryContext = nil
            Unmanaged<ChaNativeDeliveryBox>.fromOpaque(context).release()
        }
    }

    @discardableResult
    func prepareDocumentReplacement() -> String? {
        if let connectionId {
            cha_runtime_close_connection(runtime, connectionId)
            self.connectionId = nil
        }
        var error: UnsafeMutablePointer<CChar>?
        guard let opened = cha_runtime_open_connection(runtime, &error) else {
            cha_string_free(error)
            return nil
        }
        let id = String(cString: opened)
        cha_string_free(opened)
        connectionId = id
        guard let controller = webView?.configuration.userContentController else {
            return id
        }
        controller.removeAllUserScripts()
        controller.addUserScript(nativeBootstrapUserScript(connectionId: id))
        return id
    }

    func userContentController(
        _ userContentController: WKUserContentController,
        didReceive message: WKScriptMessage
    ) {
        guard message.name == chaMessageHandlerName,
              message.frameInfo.isMainFrame,
              isTrustedOrigin(message.frameInfo.securityOrigin),
              let connectionId,
              let body = message.body as? String else {
            return
        }
        connectionId.withCString { connection in
            body.withCString { json in
                cha_runtime_handle_message(runtime, connection, json)
            }
        }
    }

    func deliver(connectionId: String, json: String) {
        guard connectionId == self.connectionId, let webView else { return }
        guard let data = json.data(using: .utf8),
              let batch = try? JSONSerialization.jsonObject(with: data) else {
            return
        }
        webView.callAsyncJavaScript(
            """
            if (typeof window.__CHA_NATIVE_RECEIVE__ === "function") {
              window.__CHA_NATIVE_RECEIVE__(batch);
            } else {
              (window.__CHA_NATIVE_QUEUE__ = window.__CHA_NATIVE_QUEUE__ || []).push(batch);
            }
            """,
            arguments: ["batch": batch],
            in: nil,
            in: .page,
            completionHandler: { _ in })
    }
}
