if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "embed_text.cmake requires INPUT and OUTPUT")
endif()
file(READ "${INPUT}" CONTENT HEX)
string(LENGTH "${CONTENT}" CONTENT_LENGTH)
set(BYTES "")
if(CONTENT_LENGTH GREATER 0)
    math(EXPR LAST "${CONTENT_LENGTH} - 2")
    foreach(INDEX RANGE 0 ${LAST} 2)
        string(SUBSTRING "${CONTENT}" ${INDEX} 2 BYTE)
        string(APPEND BYTES "static_cast<char>(0x${BYTE}),")
    endforeach()
endif()
file(WRITE "${OUTPUT}" "#include <string_view>\nnamespace cha { std::string_view embedded_application_guide() { static constexpr char bytes[] = {${BYTES}0}; return {bytes, sizeof(bytes) - 1}; } }\n")
